# docker compose -f compose.dev.yaml up --build

services:
  mazanoke:
    build:
      context: .
      args:
        - ENVIRONMENT=production # development
    environment:
      - USERNAME=test
      - PASSWORD=test
    ports:
      - "3475:80"
